name: Check
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - "main"

jobs:
  test:
    name: Verify Build
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        env:
          BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun install --frozen-lock-file

      - name: Build Examples
        run: bun run build:examples
